import { readdir, readFile, mkdir, writeFile, unlink } from 'fs/promises'
import { join, dirname, relative, resolve, extname } from 'path'
import { parse } from 'es-module-lexer'
import type { Vite } from 'vitest/node'

declare global {
  type VitestModtest = typeof import('vitest')
}

// Tracks generated test files for cleanup
const GENERATED = new Set<string>()

async function* walk(directory: string, extensions: string[]): AsyncGenerator<string> {
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const res = join(directory, entry.name)
    if (entry.isDirectory()) {
      yield* walk(res, extensions)
    } else if (extensions.includes(extname(res))) {
      yield res
    }
  }
}

const checkIfFileGotTestExport = async (fullFilePath: string): Promise<boolean> => {
  const content = await readFile(fullFilePath, 'utf8')
  try {
    const [, exports] = parse(content)
    const exportList = exports.map(({ s, e }) => content.slice(s, e))
    return exportList.includes('test')
  } catch (e) {
    // Ignore files that fail to parse but log them
    console.error(`Error parsing ${fullFilePath}:`, e)
  }

  return false
}

const findFilesWithExportedTest = async (sourceDir: string, extensions: string[]): Promise<string[]> => {
  const sourcesList: string[] = []
  for await (const fullFilePath of walk(sourceDir, extensions)) {
    sourcesList.push(fullFilePath)
  }

  // Run all checks in parallel and map to results
  const exportsTest = await Promise.all(sourcesList.map(checkIfFileGotTestExport))
  return sourcesList.filter((_, i) => exportsTest[i])
}


// Note: importPath is relative to the test file
const generateTestFileCode = async (importPath: string, testFilePath: string): Promise<void> => {
  const code = `// AUTO-GENERATED by vitest-plugin-modtest
import { test as testModule } from '${importPath}'
import * as vitest from 'vitest'
if (typeof testModule !== 'function') throw new Error('No test export in ${importPath}')

await testModule(vitest)
`

  await mkdir(dirname(testFilePath), { recursive: true })
  await writeFile(testFilePath, code)

  GENERATED.add(testFilePath)
}


interface VitestPluginModtestOptions {
  srcDir?: string       // default 'src'
  testTmpDir?: string   // default: 'test/.tmp'
  extensions?: string[] // default: ['.js', '.jsx', '.ts', '.tsx']
}

const VitestPluginModtest = (options: VitestPluginModtestOptions = {}): Vite.Plugin => {
  const {
    srcDir = 'src',
    testTmpDir = 'test/.tmp',
    extensions = ['.js', '.jsx', '.ts', '.tsx']
  } = options

  const resolvedSrcDir = resolve(srcDir)
  const resolvedTestTmpDir = resolve(testTmpDir)

  /**
   * Generates the corresponding test file path for a given source file path.
   * @param fullFilePath - The absolute path to the source file.
   * @returns The absolute path to the corresponding test file with the appropriate extension.
   */
  const getTestFilePath = (fullFilePath: string): string => {
    const relPath = relative(resolvedSrcDir, fullFilePath)
    const testFilePath = join(resolvedTestTmpDir, relPath)
    return addTestExtension(testFilePath)
  }

  /**
   * Appends `.test` before the file extension of the given filename.
   * @param file The filename to modify.
   * @returns The filename with `.test` inserted before the extension.
   * @throws {Error} If the file does not have a valid extension.
   */
  const addTestExtension = (file: string): string => {
    const fileExtension = extensions.find(ext => file.endsWith(ext))
    if (!fileExtension)
      throw new Error(`File ${file} does not have a valid extension.`)
    return file.slice(0, -fileExtension.length) + `.test${fileExtension}`
  }

  /**
   * Removes a test file if it is within the test temp directory and has a valid extension.
   * @param fullFilePath Absolute path to the file to attempt to remove.
   * @returns A promise that resolves when the file is deleted or if no action is taken.
   */
  const unlinkFile = (fullFilePath: string): Promise<void> => {
    if (!GENERATED.has(fullFilePath))
      return Promise.resolve()
    if (!fullFilePath.startsWith(resolvedTestTmpDir))
      return Promise.resolve()
    if (!extensions.find(ext => fullFilePath.endsWith(`.test${ext}`)))
      return Promise.resolve()

    return unlink(fullFilePath)
      .catch((err) => {
        if ((err as any).code !== 'ENOENT')
          throw err // Ignore "file not found", rethrow others
      })
  }


  /**
   * Initiates the build process by finding all files with exported tests
   * and generating corresponding test file code for each.
   */
  const buildStart = async(): Promise<void> => {
    const files = await findFilesWithExportedTest(resolvedSrcDir, extensions)
    await Promise.all(files.map(file => {
      const fileTest = getTestFilePath(file)
      const relativeImport = relative(dirname(fileTest), file).replace(/\\/g, '/')
      return generateTestFileCode(relativeImport, fileTest)
    }))
  }

  /**
   * Cleans up all generated test files by deleting them.
   */
  const closeBundle = async(): Promise<void> =>{
    // Cleanup all generated test files
    await Promise.all([...GENERATED].map(fileTest => unlinkFile(fileTest)))
  }

  /**
   * Handles file changes during development and updates generated test files as needed.
   */
  const configureServer = (server: Vite.ViteDevServer) => {
      // Watch for changes to .js files in src/
      server.watcher.on('change', async (fullFilePath) => {
        if (!fullFilePath.startsWith(resolvedSrcDir))
          return
        if (!extensions.find(ext => fullFilePath.endsWith(ext)))
          return

        if (!fullFilePath.startsWith(resolvedTestTmpDir)) {
          const fileTest = getTestFilePath(fullFilePath)
          const relativeImport = relative(dirname(fileTest), fullFilePath).replace(/\\/g, '/')
          const modTest = server.moduleGraph.getModuleById(fileTest)
          const modRel =  server.moduleGraph.getModuleById(relativeImport)

          if (await checkIfFileGotTestExport(fullFilePath)) {
            await generateTestFileCode(relativeImport, fileTest)
          } else if (GENERATED.has(fileTest)) {
            await unlinkFile(fileTest)
            GENERATED.delete(fileTest)
            server.watcher.emit('unlink', fileTest)
          }

          for (const oneMod of [modTest, modRel]) {
            if (oneMod)
              server.moduleGraph.invalidateModule(oneMod)
          }

        }
      })
    }

  return {
    name: 'vitest-pluginmodtest',
    buildStart,
    closeBundle,
    configureServer
  }
}

export default VitestPluginModtest
